# TODO: automate generation of this file
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: daily
