name: "Setup HashiCorp Releases"
description: "Download and setup binary from releases.hashicorp.com in a GitHub Actions build environment"
author: "Bloomin' Labs"
inputs:
  package:
    description: "Name of the package to install"
    required: true
  version:
    description: "Version of the package to install, or 'latest' (default). This accepts semver ranges like ^3.0.0."
    required: true
    default: "latest"
branding:
  icon: "terminal"
  color: "purple"
runs:
  using: "node16"
  main: "dist/setup/index.js"
  post: "dist/cache-save/index.js"
