name: "Test action-install-envconsul"
on:
  pull_request:
  push:
    branches:
      - "main"
      - "releases/*"

jobs:
  unit:
    name: Unit Test
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest] #, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/setup-node@v1
        with:
          cache: ${{ !env.ACT && 'yarn' || '' }}
          node-version: "16.x"
      - uses: actions/checkout@v2
      - run: yarn install --frozen-lockfile --ignore-optional
      - run: yarn test
  latest:
    name: Test Latest Version Install
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest] #, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/setup-node@v1
        with:
          cache: ${{ !env.ACT && 'yarn' || '' }}
          node-version: "16.x"
      - uses: actions/checkout@v2
      - run: yarn install --frozen-lockfile --ignore-optional
      - run: yarn package
      - uses: ./
        with:
          package: envconsul
      - run: envconsul --version
  specific:
    name: Test Specific Version Install
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest] #, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/setup-node@v1
        with:
          cache: ${{ !env.ACT && 'yarn' || '' }}
          node-version: "16.x"
      - uses: actions/checkout@v2
      - run: yarn install --frozen-lockfile --ignore-optional
      - run: yarn package
      - uses: ./
        with:
          package: envconsul
          version: 0.11.0
      - run: envconsul --version
  patch-range:
    name: Test Patch Range Version Install
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest] #, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/setup-node@v1
        with:
          cache: ${{ !env.ACT && 'yarn' || '' }}
          node-version: "16.x"
      - uses: actions/checkout@v2
      - run: yarn install --frozen-lockfile --ignore-optional
      - run: yarn package
      - uses: ./
        with:
          package: envconsul
          version: 0.12.*
      - run: envconsul --version
  major-range:
    name: Test Patch Range Version Install
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest] #, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/setup-node@v1
        with:
          cache: ${{ !env.ACT && 'yarn' || '' }}
          node-version: "16.x"
      - uses: actions/checkout@v2
      - run: yarn install --frozen-lockfile --ignore-optional
      - run: yarn package
      - uses: ./
        with:
          package: envconsul
          version: ^0.12.1
      - run: envconsul --version
