name: "Test action-install-envconsul"
on:
  pull_request:
  push:
    branches:
      - "main"
      - "releases/*"

jobs:
  unit:
    name: Unit Test
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest] #, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          cache: ${{ !env.ACT && 'pnpm' || '' }}
          node-version: "16.x"
      - run: pnpm install --frozen-lockfile
      - run: pnpm test
  latest:
    name: Test Latest Version Install
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest] #, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          cache: ${{ !env.ACT && 'pnpm' || '' }}
          node-version: "16.x"
      - run: pnpm install --frozen-lockfile
      - run: pnpm package
      - uses: ./
        with:
          package: envconsul
      - run: envconsul --version
  specific:
    name: Test Specific Version Install
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest] #, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          cache: ${{ !env.ACT && 'pnpm' || '' }}
          node-version: "16.x"
      - run: pnpm install --frozen-lockfile
      - run: pnpm package
      - uses: ./
        with:
          package: envconsul
          version: 0.11.0
      - run: envconsul --version
  patch-range:
    name: Test Patch Range Version Install
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest] #, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          cache: ${{ !env.ACT && 'pnpm' || '' }}
          node-version: "16.x"
      - run: pnpm install --frozen-lockfile
      - run: pnpm package
      - uses: ./
        with:
          package: envconsul
          version: 0.12.*
      - run: envconsul --version
  major-range:
    name: Test Patch Range Version Install
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest] #, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          cache: ${{ !env.ACT && 'pnpm' || '' }}
          node-version: "16.x"
      - run: pnpm install --frozen-lockfile
      - run: pnpm package
      - uses: ./
        with:
          package: envconsul
          version: ^0.12.1
      - run: envconsul --version

  nomad:
    name: Test Nomad Install
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest] #, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          cache: ${{ !env.ACT && 'pnpm' || '' }}
          node-version: "16.x"
      - run: pnpm install --frozen-lockfile
      - run: pnpm package
      - uses: ./
        with:
          package: nomad
          version: latest
      - run: nomad version

  packer:
    name: Test Packer Install
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest] #, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          cache: ${{ !env.ACT && 'pnpm' || '' }}
          node-version: "16.x"
      - run: pnpm install --frozen-lockfile
      - run: pnpm package
      - uses: ./
        with:
          package: packer
          version: latest
      - run: packer version

  consul:
    name: Test Consul Install
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest] #, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          cache: ${{ !env.ACT && 'pnpm' || '' }}
          node-version: "16.x"
      - run: pnpm install --frozen-lockfile
      - run: pnpm package
      - uses: ./
        with:
          package: consul
          version: v1.12.0
      - run: consul version

  vault:
    name: Test Vault Install
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest] #, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          cache: ${{ !env.ACT && 'pnpm' || '' }}
          node-version: "16.x"
      - run: pnpm install --frozen-lockfile
      - run: pnpm package
      - uses: ./
        with:
          package: vault
          version: v1.10.1
      - run: vault version

  consul-template:
    name: Test consul-template Install
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest] #, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          cache: ${{ !env.ACT && 'pnpm' || '' }}
          node-version: "16.x"
      - run: pnpm install --frozen-lockfile
      - run: pnpm package
      - uses: ./
        with:
          package: consul-template 
          version: v0.30.0
      - run: consul-template --version

  sentinel:
    name: Test Sentinel Install
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest] #, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          cache: ${{ !env.ACT && 'pnpm' || '' }}
          node-version: "16.x"
      - run: pnpm install --frozen-lockfile
      - run: pnpm package
      - uses: ./
        with:
          package: sentinel
          version: v0.19.5
      - run: sentinel --version
